### PR TITLE
Negative  numbers on red

### PR DESCRIPTION
**Pull request by jortilles**
One common annoying question i'm usually having from customers is ... Why negative numbers are not in red?  Negative numbers are always in red.

This could be done quite easily like this....

### CODE REVIEW

**Comment by jortilles** [comment]
You use local storage to store cube definition. 
When you have huge cubes with lots of dimensions and levels , the local storage can be too small to store all the information. Looking how you store the information i found you store the the html as is.
 
In that html there are a lot of useless white spaces. So i'm cleaning  them by removing all the concatenation of 3 white spaces in the html string.
I assume nobody will use e white spaces dimension or level name like "foo   var"

**Comment by brenopolanski** [comment]
Hey @jortilles interesting things about **whitespaces in the local storage**. I have been looking over the max storage size and I found this:

### Desktop browsers:

```
Browser    | Chrome   | Opera    | Firefox    | Safari      | IE
Version    | 40       | 27       | 34         | 6-8         | 9-11
Available  | 10MB     | 10MB     | 10MB       | 5MB         | 10MB
```

**Comment by brenopolanski** [comment]
Hey @jortilles any news?

**Comment by brenopolanski** [comment]
Okay @jortilles I did a merge and fixed your code! See the commit https://github.com/OSBI/saiku/commit/55e406a58f102cb0fff9a8b7aac3a4eb345bc094 and https://github.com/OSBI/saiku/commit/d4de075777ceebf25200f6dec76f222673284bb1

Thanks :+1:

**Comment by jortilles** [comment]
Hey Breno.

I was with a bit of mess ...

Thanks you did it

Juanjo Ortilles - Open Business Analytics
twitter: jortilles
www.jortilles.com / es / cat

2018-04-16 19:55 GMT+02:00 Breno Polanski <notifications@github.com>:

**Pull request closed without merging**
