### PR TITLE
Added ability to set datasource and connection processors to RepositoryDatasourceManager

### PR DESCRIPTION
**Pull request by kynx**
This PR addresses #683,  enabling administrators to add `IDatasourceProcessor` and `IConnectionProcessor` instances to the repository datasource manager via saiku-beans.xml.

For example:
```
    <bean id="repositoryDsManager" class="org.saiku.service.datasource.RepositoryDatasourceManager" init-method="load" destroy-method="unload">
        <!-- other properties /-->

        <property name="datasourceProcessor" value="com.example.MyDatasourceProcessor"/>
        <property name="connectionProcessor" value="com.example.MyConnectionProcessor"/>
    </bean>

<!-- snip -->

<bean id="myDatasourceProcessor" class="com.example.MyDatasourceProcessor"/>

<bean id="connectionManager" class="org.saiku.web.core.SecurityAwareConnectionManager" init-method="init"
          destroy-method="destroy" depends-on="mondrianVFS">
        <!-- other properties /-->

        <property name="dataSourceProcessors">
            <list value-type="org.saiku.service.datasource.IDatasourceProcessor">
                <ref bean="myDatasourceProcessor" />
            </list>
        </property>
    </bean>
```

I've included tests to verify the correct properties are added to the datasource and manually checked that the processors are actually called. 

I'm sorely tempted to automatically set the `security.enabled` property when either of these are added, but I'm not 100% sure of the knock-on from that.

### CODE REVIEW

**Comment by buggtb** [comment]
Hey @kynx thanks for the PR. I've asked one of guys to triage them and they tell me they should get around to it over the weekend.

**Comment by brunogamacatao** [comment]
Thanks @kynx for all your contributions. The other bugfixes and improvements to spring/maven config files were approved, thanks a lot. This one, seems very interesting, but we need to test it a little bit more before merging it.
Good job !

**Comment by kynx** [comment]
Thanks @brunogamacatao. Setting this up on clean machine on the weekend I realised I'd left some stuff out of the config example. I've updated the description above.

**Comment by brunogamacatao** [comment]
Great. 
I'm gonna test it again.

**Pull request merged**
