### PR TITLE
SKU-1537 #Changed table rendering and added button to collapse and ex…

### PR DESCRIPTION
**Pull request by bftcore**
#Changed table rendering and added button to collapse and expand rows for compact table view

### CODE REVIEW

**Comment by buggtb** [comment]
Hi, I'll accept the request if you disable it by default and putting a setting in Settings.js to enable it, for most people it doesn't make sense to have a table do this.

**Comment by bftcore** [comment]
Hi,
Ok, I’ll do it soon

--
Arseniy Gshyan

**Comment by bftcore** [comment]
Hi,
How soon you accept this request?

**Comment by brenopolanski** [comment]
hey @bftcore I tested your modification, but you need solve the code conflicts in `saiku-ui/js/saiku/Settings.js`. Please fix it and i'll do the merge ;)

**Pull request merged**
