### PR TITLE
Removing string 'Bla' from excel worksheet

### PR DESCRIPTION
**Pull request by enludovi**
saiku-core/saiku-service/src/main/java/org/saiku/service/util/export/excel/ExcelWorksheetBuilder.java

```

--- a/saiku-core/saiku-service/src/main/java/org/saiku/service/util/export/excel/ExcelWorksheetBuilder.java
+++ b/saiku-core/saiku-service/src/main/java/org/saiku/service/util/export/excel/ExcelWorksheetBuilder.java
@@ -248,7 +248,8 @@ public class ExcelWorksheetBuilder {
                     // Measure aggregator
                     cell = row.createCell(1);
                     cell.setCellStyle(basicCS);
-                    cell.setCellValue(agg.getClass().getSimpleName().substring(0, 3));
+                    //cell.setCellValue(agg.getClass().getSimpleName().substring(0, 3));
+                    cell.setCellValue(agg.getFormattedValue());                    
                 }
             }
         }
@@ -286,7 +287,8 @@ public class ExcelWorksheetBuilder {
                         // Measure aggregator
                         cell = row.createCell(1);
                         cell.setCellStyle(basicCS);
-                        cell.setCellValue(agg.getClass().getSimpleName().substring(0, 3));
+                        //cell.setCellValue(agg.getClass().getSimpleName().substring(0, 3));
+                        cell.setCellValue(agg.getFormattedValue());
                     }
                 }
             }
@@ -334,7 +336,6 @@ public class ExcelWorksheetBuilder {
     }

     private void initSummarySheet() {
-
         // Main Workbook Sheet
         Sheet summarySheet = excelWorkbook.createSheet("Summary page");



```

### CODE REVIEW

**Comment by enludovi** [comment]
```
--- a/saiku-core/saiku-service/src/main/java/org/saiku/service/olap/ThinQueryService.java
+++ b/saiku-core/saiku-service/src/main/java/org/saiku/service/olap/ThinQueryService.java
@@ -539,41 +539,67 @@ public class ThinQueryService implements Serializable {
         }
         String[] simpleHeader = new String[width];
         AbstractBaseCell[][] cellHeaders = null;
-        if (StringUtils.isBlank(returns)) {                 
+        
+        if (StringUtils.isBlank(returns)) {
             //CellDataSet result = OlapResultSetUtil.cellSet2Matrix(cs, cff.forName(StringUtils.EMPTY));          
             //cellHeaders = result.getCellSetHeaders();             
-
             for(int i=0, k=1; i< width; i++, k++) {
                 try {
                     simpleHeader[i] = drillthrough.getMetaData().getColumnLabel(k);                
                 } catch (SQLException ex) {
                     java.util.logging.Logger.getLogger(ThinQueryService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                 }
-            }                      
-        } else {         
+            }
+        } else {
             List<ResultInfo> results = DrillthroughUtils.extractResultInfo(returns);
+        
+            Map<String,String> h = new HashMap<>();
             for (int i = 0; i < results.size(); i++) {
                 final ResultInfo ri = results.get(i);
+                
                 if (ri instanceof MeasureResultInfo) {
                     simpleHeader[i] = DrillthroughUtils.findMeasure(measures, ((MeasureResultInfo) ri).getName()).getCaption();
                 } else if (ri instanceof DimensionResultInfo) {
                     final DimensionResultInfo dri = (DimensionResultInfo) ri;
-                    List<SaikuHierarchy> hierarchies = olapDiscoverService
-                            .getDimension(saikuCube, dri.getDimension()).getHierarchies();
+                    
+                    List<SaikuHierarchy> hierarchies = 
+                            olapDiscoverService.getDimension(saikuCube, dri.getDimension()).getHierarchies();
                     SaikuHierarchy hierarchy = null;
+                    
                     try {
-                        hierarchy = DrillthroughUtils
-                            .findHierarchy(hierarchies, dri.getHierarchy());
+                        hierarchy = 
+                                DrillthroughUtils.findHierarchy(hierarchies, dri.getHierarchy());
                     }
                     catch(Exception e){
-                        hierarchy = DrillthroughUtils
-                            .findHierarchy(hierarchies, dri.getDimension()+"."+dri.getHierarchy());
+                        hierarchy = 
+                                DrillthroughUtils.findHierarchy(hierarchies, dri.getDimension()+"."+dri.getHierarchy());
                     }                  
                     SaikuLevel level = DrillthroughUtils.findLevel(hierarchy.getLevels(), dri.getLevel());
-                    simpleHeader[i] = level.getCaption();
+
+                    ///simpleHeader[i] = level.getCaption();        
+                    
+                    h.put(level.getUniqueName(), level.getCaption());
                 }
             }
+
+            for(int i=0, k=1; i< width; i++, k++) {
+                try {
+                    String columnLabel = drillthrough.getMetaData().getColumnLabel(k);
+                    String currentCaption = h.get(columnLabel);
+                    
+                    if(currentCaption == null) {
+                        simpleHeader[i] = columnLabel;
+                    } else {
+                        simpleHeader[i] = currentCaption;
+                    }                   
+                } catch (SQLException ex) {
+                    java.util.logging.Logger.getLogger(ThinQueryService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
+                }
+            }     
+ 
+            
         }
+        
         return new DrillThroughResult(drillthrough, simpleHeader, cellHeaders);
     }

```

**Comment by enludovi** [comment]
```

--- a/saiku-ui/js/saiku/views/WorkspaceToolbar.js
+++ b/saiku-ui/js/saiku/views/WorkspaceToolbar.js
@@ -495,9 +495,9 @@ var WorkspaceToolbar = Backbone.View.extend({
 
     export_xls: function(event) {
 		if(this.workspace.query.name!=undefined){
-			var filename = this.workspace.query.name.substring(this.workspace.query.name.lastIndexOf('/')+1).slice(0, -5);
+			var filename = this.workspace.query.name.substring(this.workspace.query.name.lastIndexOf('/')+2).slice(0, -5);
 			window.location = Settings.REST_URL +
-			this.workspace.query.url() + "/export/xls/" + this.workspace.query.getProperty('saiku.olap.result.formatter')+"?exportname=" + encodeURIComponent(filename)+"xls";
+			this.workspace.query.url() + "/export/xls/" + this.workspace.query.getProperty('saiku.olap.result.formatter')+"?exportname=" + encodeURIComponent(filename)+"xlsx";
 		}
 		else{
 			window.location = Settings.REST_URL +
@@ -509,7 +509,7 @@ var WorkspaceToolbar = Backbone.View.extend({
 
     export_csv: function(event) {
 		if(this.workspace.query.name!=undefined){
-			var filename = this.workspace.query.name.substring(this.workspace.query.name.lastIndexOf('/')+1).slice(0, -6);
+			var filename = this.workspace.query.name.substring(this.workspace.query.name.lastIndexOf('/')+2).slice(0, -6);
 			window.location = Settings.REST_URL +
 			this.workspace.query.url() + "/export/csv/" + this.workspace.query.getProperty('saiku.olap.result.formatter')+"?exportname=" + encodeURIComponent(filename);
 		}
@@ -523,7 +523,7 @@ var WorkspaceToolbar = Backbone.View.extend({
 
     export_pdf: function(event) {
 		if(this.workspace.query.name!=undefined){
-			var filename = this.workspace.query.name.substring(this.workspace.query.name.lastIndexOf('/')+1).slice(0, -6);
+			var filename = this.workspace.query.name.substring(this.workspace.query.name.lastIndexOf('/')+2).slice(0, -6);
 			window.location = Settings.REST_URL +
 			this.workspace.query.url() + "/export/pdf/" + this.workspace.query.getProperty('saiku.olap.result.formatter')+"?exportname=" + encodeURIComponent(filename);
 		}



```

**Comment by qixiaobo** [comment]
@enludovi  You should  sign the Contributor License Agreement. 
https://www.clahub.com/agreements/OSBI/saiku

**Comment by enludovi** [comment]
I already signed it.

**Pull request merged**
