### PR TITLE
put extra quotes around the filename

### PR DESCRIPTION
**Pull request by enricomariam42**
ref: https://github.com/OSBI/saiku/issues/634
Compiled and tested saiku-bi-platform-plugin-p7.1 in pentaho server 7.1
image

### CODE REVIEW

**Comment by brenopolanski** [comment]
@brunogamacatao can you see this PR please?

Test it in:

- [ ] Windows - Chrome, Firefox and Edge
- [ ] Linux - Chrome and Firefox
- [ ] Saiku Standalone
- [ ] Saiku plugin for Pentaho

**Comment by brenopolanski** [comment]
@enricomariam42 Can you rebase this PR against `hotfix-3.16.1` please?

**Comment by enricomariam42** [comment]
@brenopolanski I created PR #641 against hotfix-3.16.1 (I hope it's ok)

**Comment by enricomariam42** [comment]
@brenopolanski I finally figured how did it in this PR. Sorry for the mess. :P

**Comment by buggtb** [comment]
Thanks for the patch!

**Pull request merged**
